### ISSUE TITLE
"No write since last change" when "Already at oldest change"

### ISSUE THREAD

**Issue by vimeitor** [easymotion/vim-easymotion#117]
Hello,

I'm not a hundred percent sure this is caused by easymotion, but I would say it is, because I only reproduce it when I use easymotion and happened after a recent update.

When I use easymotion (jump to a certain position) and undo until I get "Already at oldest change" and try to quit vim, I get "No write since last change". This happens even if I haven't modified a single character of the text and have only jumped around with easymotion.

I have recorded the terminal showing the issue. I'm sorry if you can't see it really well: https://asciinema.org/a/7787

Take care,

Adria

**Comment by haya14busa** [comment]
It seems it's fixed now

**Comment by net** [comment]
It's not fixed. Occurs as expected.

Neovim 0.2.0, EasyMotion 3.0.1.
