### ISSUE TITLE
`easymotion-overwin` echo `No matching autocommands`

### ISSUE THREAD

**Issue by SolaWing** [easymotion/vim-easymotion#294]
After I tested, the cause is `doautocmd WinLeave`, my WinLeave event has only one pattern for `__Tagbar__`, this cause `exists('#WinLeave')` return 1, but call `doautocmd *` echoes  `No matching autocommands`.

Further more, `exists('#WinLeave#*')` return 0. `#event#pattern` check pattern literally, if I define pattern `*` for WinLeave, except `('#WinLeave#*')`, other checks like `('#WinLeave#filename')` all return 0.
This means noway to check if there is a match pattern match current filename.

My quick fix is change `doautocmd WinLeave *` to `silent doautocmd WinLeave`. I also change `doautocmd WinEnter *`.   This will suppress `No matching autocommands`. Also notice I removed `*`, `doautocmd WinLeave *` will not invoke pattern like `*.vim` when I'm in a vim buffer. Removing it cause pattern default to current name, and all match pattern will be called.

**Comment by unclechu** [comment]
Adding this to my neovim config fixes this issue:
```
autocmd WinLeave * silent
```

**Comment by haya14busa** [comment]
I cannot reproduce this. What is __Tagbar__ autocmd??? Please reopen with more detail reproduction steps.

**Comment by SolaWing** [comment]
Reproduce step:

1. first: 
```vim
autocmd WinLeave *.c silent
```
2. run `autocmd WinLeave` and see output to ensure WinLeave event don't contains a `*` pattern
3. do overwin motion.
4. `No matching autocommands`  was echoed.

PS: `doautocmd WinLeave *` only match a literary `*`, it **doesn't** match any other specific file patten like `abc.py` or `*.py`, `doautocmd WinLeave` is default to current file name and is more sensible

**Comment by haya14busa** [comment]
Thanks! I fixed it. #314

**Comment by SolaWing** [comment]
@haya14busa  Issue still exist, when define
```vim
 autocmd WinLeave *.c silent
```
`exists('#WinLeave')` return 1  

but `doautocmd WinLeave` can't find a match and echo message when current file is not `*.c` file

To Fix:

**silent** `doautocmd`

or ensure always have a match with `autocmd WinLeave * silent`
